In [1]:
import numpy as np

In [4]:
T = np.array([[0.6, 0.3, 0.1],[0.5, 0.3, 0.2],[0.2, 0.1, 0.7]])

In [9]:
T @ T

array([[0.53, 0.28, 0.19],
       [0.49, 0.26, 0.25],
       [0.31, 0.16, 0.53]])

In [18]:
np.linalg.matrix_power(T, 2000) ## This is called stationary distribution!!!!

array([[0.45238095, 0.23809524, 0.30952381],
       [0.45238095, 0.23809524, 0.30952381],
       [0.45238095, 0.23809524, 0.30952381]])

In [67]:
States = ["Rainy", "Cloudy", "Sunny"]
states_enumerated = {i:j for i,j in enumerate(States)}
states = [i for i in range(3)]

In [68]:
def sample(current_state, states = states, trainsition_probs = T):
    return np.random.choice(states, p = T[current_state, :]    

In [88]:
def generate_chain(initial_state = 0, length = 100,states = states, transition_probs = T):
    chain = [initial_state]
    for i in range(length):
        next_state = sample(chain[-1], states, transition_probs)
        chain.append(next_state)
    return chain        

In [95]:
chain = generate_chain()

In [111]:
length = 10000
np.bincount(generate_chain(length = length))/length

array([0.451 , 0.2412, 0.3079])